FROM docker.io/postgres:16

# Install pgvector extension
RUN apt-get update && \
    apt-get install -y \
    postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*

COPY ./compose/production/postgres/maintenance /usr/local/bin/maintenance
RUN chmod +x /usr/local/bin/maintenance/*
RUN mv /usr/local/bin/maintenance/* /usr/local/bin \
    && rmdir /usr/local/bin/maintenance
